### ISSUE TITLE
Callback every minute

### ISSUE THREAD

**Issue by sepehr1014** [SageAnalytic/Revalee#6]
Here's my scenario: We have a small mailing list (a couple of thousands) and we send daily/weekly/monthly emails to them. So we have a table called OutgoingEmails that contains emails that are to be sent (with address, subject, body and due dates specified) and we have a function that takes care of sending the emails. This function needs to be called every 20 seconds (So that there's about 20 seconds of delay between each email sent).

So how can we schedule a callback to be called every 20 seconds? Or is there a better solution to our needs?

**Comment by BrianMullin** [comment]
Revalee is typically used when scheduling each individual email message ahead of time. The benefits are you don't require a queuing system, a mechanism to throttle frequency, or tracking system to ensure each task is only executed once.

Since you have a sending queue already, you could start up a System.Threading.Timer upon application startup. Set the timer to fire every 20 seconds. When timer event triggers, 1. query the emails that you want to send from the OutgoingEmails table, 2. compose the email message(s), 3. send the email message(s), and 4. delete the processed row(s) from the OutgoingEmails table.

**Comment by sepehr1014** [comment]
I see. But I'm pretty sure starting up a timer upon application startup is not a viable solution since IIS kills application pool whenever it feels like.
I could however schedule a callback every minute, and start a timer to send 3 emails ...

I was wondering if there's a better way.

**Comment by BrianMullin** [comment]
You can run the whole email sending mechanism on the 30 second timer. Schedule a Revalee callback every 1 minute to ensure the web application is running (the callback will force IIS to restart it if the web application has been shutdown). When restarting, the 30 second timer will be reestablished.

**Comment by sepehr1014** [comment]
Yes, that would be a good approach I guess.

**Comment by sepehr1014** [comment]
Yes, that would be a good approach I guess.
